### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ShotaKitazawa** [ShotaKitazawa/isucontinuous#1]
- [x] init コマンド
    - [x] 以下のフォーマットのファイルを `$HOME/isucon-repo` に生成
      ```yaml
      setup:
        docker:
          netdata:
            version: latest
            public_port: 19999
        alp:
          version: v1.0.8
      slack:
        default_channel: ""
      hosts:
      - host: localhost
        user: root
        key: /root/.ssh/id_rsa
        deploy:
          slack_channel: ""
          pre_command: >
            rm -f "${env.ACCESSLOG_PATH}";
            rm -f "${env.SLOWLOG_PATH}";
          post_pommand: >
            sudo systemctl restart isucondition.go.service
          targets:
          - src: nginx
            target: /etc/nginx
          - src: mysql
            target: /etc/mysql
          - src: go
            target: /home/isucon/webapp/go
            compile: make
        profile:
          command: go tool pprof --output {{.env.HOME}}/pprof/profile-{{.Git.CommitHash}}.pb.gz http://localhost:3000/debug/pprof/profile?seconds=90
        after_bench:
          slack_channel: ""
          target: /profile/{{.Git.CommitHash}}/
          command: >
            mkdir -p /profile/{{.Git.CommitHash}};
            if [ -f {{.env.HOME}}/pprof/profile-{{.Git.CommitHash}}.pb.gz ]; then
              go tool pprof -top {{.env.HOME}}/pprof/profile-{{.Git.CommitHash}}.pb.gz > /profile/{{.Git.CommitHash}}/pprof_top;
            fi;
            cat "{{.env.ACCESSLOG_PATH}}" | alp ltsv -r --sort sum > /profile/{{.Git.CommitHash}}/accesslog;
            cat "{{.env.SLOWLOG_PATH}}" | docker run -i --rm matsuu/pt-query-digest > /profile/{{.Git.CommitHash}}/slowlog;
      ```
    - [x] `git init` のオプションに与えた URL を `git config` でセットする

- [x] setup コマンド
    - [x] Docker のインストール
    - [x] alp のインストール

- [x] import コマンド
    - [x] isucontinuous.yaml の `targets[].deploy.files[].target` を `$HOME/isucon-repo` に移動
    - [x] .gitignore を無視する
    - [x] local-repo が remote repo の main HEAD でない場合エラーを出力する

- [x] push コマンド
    - [x] local-repo にて `git commit -a && git push` する
    - [x] local-repo が remote repo の main HEAD でない場合エラーを出力する

- [x] sync コマンド
    - [x] local repo を remote repo の main HEAD に合わせる (競技中に新たに import を実行したいときに利用)

- [x] deploy コマンド
    - [x] git fetch && git switch -d
    - [x] isucontinuous.yaml を読んで各種処理を実施
    - [x] targets ごとに並列処理
    - [x] Slack に通知
    - [x] 他のユーザが deploy, profile, afterbench 実行中は実行できないようにする

- [x] profile コマンド
    - [x] 各サーバで command を実行
    - [x] 全サーバから command が戻ってきたら実行を終了する

- [x] afterbench コマンド
    - [x] command を実行
    - [x] /profile 以下のファイルを slack に送信
